# Generated by Django 5.1.5 on 2025-01-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
